### PR TITLE
Remove some dead rules; refactor format/lint logic into an API.

### PR DESCRIPTION
**Pull request by allevato**
This moves much of the logic for performing a format/lint operation from
the command line tool and into a new module, "SwiftFormat", which is
intended to be used by anyone who wants to format or lint Swift code.
This will support integrating it into other tools in a better way than
shelling out to the command line.

### CODE REVIEW

**Comment by dabelknap** [comment]
`generate-pipeline.swift` also needs to be updated so it puts the `PopulatePipeline.swift` file in the right place, now that it has been moved.

**Comment by allevato** [comment]
> `generate-pipeline.swift` also needs to be updated so it puts the `PopulatePipeline.swift` file in the right place, now that it has been moved.

Good catch, thanks! Done.

**Comment by dabelknap** [comment]
@allevato I didn't realize this until after I merged it, but running the formatter in format mode from the command line does not output anything.

**Comment by allevato** [comment]
@dabelknap I just tried it with `Package.swift` and it prints part of the output but then gets cut off. A smaller file gives the behavior you're seeing. So it looks like a buffering issue with the switchover to the new `TextOutputStream`-based API—I'll get a fix out shortly.

**Pull request merged**
